# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54e67eba5da8af774f6b67d1756c64e4d48c6064f715999e5ef1fb75b2e2df140846f73566169a77c49beafd0cdd9bb0805d6d2b7a717333bad4c575225e6f29

test:
  secret_key_base: 0eb2d91ab2947d105275f7a7c9e6404e71b92cd90ce4e13b79661f964d8b0391284d0e7e5a8412c3a0985d9809e3c5220055d28e093f607b2175e1455955e5f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
